[build]
  command = "node scripts/prepare-netlify-sharp.mjs && node scripts/prepare-netlify-ffmpeg.mjs && npm run build"
  publish = ".next"

[functions]
  external_node_modules = ["sharp"]
  included_files = [
    "node_modules/aid-netlify-ffmpeg/**",
  "node_modules/@img/sharp-linux-x64/**",
    "node_modules/@img/sharp-libvips-linux-x64/**"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
