// Split a 3x3 grid image into 9 individual images using Canvas
// Each cell has the same aspect ratio as the whole grid
export async function splitGridImage(
  imageUrl: string,
  aspectRatio: '16:9' | '9:16' | '1:1' = '16:9'
): Promise<string[]> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const cellWidth = Math.floor(img.width / 3);
      const cellHeight = Math.floor(img.height / 3);
      // Inset to skip border/separator pixels generated by AI
      const inset = Math.max(0, Math.round(Math.min(cellWidth, cellHeight) * 0.045)); // ~1.5% of full width
      const cells: string[] = [];

      try {
        for (let row = 0; row < 3; row++) {
          for (let col = 0; col < 3; col++) {
            const sx = col * cellWidth + inset;
            const sy = row * cellHeight + inset;
            const sw = cellWidth - inset * 2;
            const sh = cellHeight - inset * 2;
            const canvas = document.createElement('canvas');
            canvas.width = sw;
            canvas.height = sh;
            const ctx = canvas.getContext('2d');
            if (!ctx) throw new Error('Failed to get canvas context');
            ctx.drawImage(img, sx, sy, sw, sh, 0, 0, sw, sh);
            cells.push(canvas.toDataURL('image/jpeg', 0.95));
          }
        }
        resolve(cells);
      } catch (error) {
        reject(error instanceof Error ? error : new Error('Failed to split grid image'));
      }
    };
    img.onerror = () => reject(new Error('Failed to load grid image'));
    img.src = imageUrl.startsWith('data:')
      ? imageUrl
      : `/api/proxy-image?url=${encodeURIComponent(imageUrl)}`;
  });
}

// Build the 3x3 grid prompt for a given set of storyboards
export function buildGridPrompt(
  sceneStyle: string,
  characterDescriptions: string,
  shotDescriptions: string[],
  aspectRatio: '16:9' | '9:16' | '1:1',
  referenceImageLabels?: string[] // e.g. ['TOTODA (ref image 1)', 'MOMODA (ref image 2)']
): string {
  const orientation = aspectRatio === '9:16' ? 'vertical portrait' : aspectRatio === '1:1' ? 'square' : 'horizontal landscape';
  const shots = shotDescriptions.slice(0, 9).map(shot => {
    const requirementIndex = shot.indexOf('REQUIRED CHARACTERS');
    if (requirementIndex === -1 || shot.length <= 320) return shot;
    const requirements = shot.slice(requirementIndex);
    const visualBudget = Math.max(80, 320 - requirements.length - 1);
    return `${shot.slice(0, visualBudget).trim()} ${requirements}`;
  });
  while (shots.length < 9) shots.push(shots[shots.length - 1] || 'medium shot');

  const refSection = referenceImageLabels && referenceImageLabels.length > 0
    ? `\nReference image mapping:\n${referenceImageLabels.map((label, i) => `- Reference image ${i + 1}: ${label}`).join('\n')}\n`
    : '';

  return `Generate one 3x3 cinematic storyboard contact sheet. Each panel is ${orientation} (${aspectRatio}). Arrange panels left-to-right, top-to-bottom with no borders, gaps, separator lines, labels, captions, or text.

Scene environment: ${sceneStyle}
${refSection}
Character identities (match mapped references exactly wherever they appear):
${characterDescriptions}

Panel 1: ${shots[0]}
Panel 2: ${shots[1]}
Panel 3: ${shots[2]}
Panel 4: ${shots[3]}
Panel 5: ${shots[4]}
Panel 6: ${shots[5]}
Panel 7: ${shots[6]}
Panel 8: ${shots[7]}
Panel 9: ${shots[8]}

CRITICAL CAST RULES:
- Every REQUIRED CHARACTERS entry must be clearly visible in its panel. Never omit, replace, merge, or hide one as a background detail.
- Animals and non-human characters are full characters, not props. A required cat must visibly match its reference identity, fur, markings, size, and species.
- Do not add characters to panels where they are not requested. Preserve each character's exact reference appearance across panels.

Keep lighting and environment continuous. Each cell must be a complete standalone composition, never a cropped fragment.`;
}
