// Split a 3x3 grid image into 9 individual images using Canvas
// Each cell has the same aspect ratio as the whole grid
export async function splitGridImage(
  imageUrl: string,
  aspectRatio: '16:9' | '9:16' | '1:1' = '16:9'
): Promise<string[]> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const cellWidth = img.width / 3;
      const cellHeight = img.height / 3;
      // Inset to skip border/separator pixels generated by AI
      const inset = Math.round(img.width * 0.015); // ~1.5% of width to skip separator lines
      const cells: string[] = [];

      for (let row = 0; row < 3; row++) {
        for (let col = 0; col < 3; col++) {
          const sx = col * cellWidth + inset;
          const sy = row * cellHeight + inset;
          const sw = cellWidth - inset * 2;
          const sh = cellHeight - inset * 2;
          const canvas = document.createElement('canvas');
          canvas.width = sw;
          canvas.height = sh;
          const ctx = canvas.getContext('2d')!;
          ctx.drawImage(img, sx, sy, sw, sh, 0, 0, sw, sh);
          cells.push(canvas.toDataURL('image/jpeg', 0.95));
        }
      }
      resolve(cells);
    };
    img.onerror = () => reject(new Error('Failed to load grid image'));
    img.src = imageUrl;
  });
}

// Build the 3x3 grid prompt for a given set of storyboards
export function buildGridPrompt(
  sceneStyle: string,
  characterDescriptions: string,
  shotDescriptions: string[],
  aspectRatio: '16:9' | '9:16' | '1:1',
  referenceImageLabels?: string[] // e.g. ['TOTODA (ref image 1)', 'MOMODA (ref image 2)']
): string {
  const orientation = aspectRatio === '9:16' ? 'vertical portrait' : aspectRatio === '1:1' ? 'square' : 'horizontal landscape';
  const shots = shotDescriptions.slice(0, 9);
  while (shots.length < 9) shots.push(shots[shots.length - 1] || 'medium shot');

  const refSection = referenceImageLabels && referenceImageLabels.length > 0
    ? `\nReference image mapping:\n${referenceImageLabels.map((label, i) => `- Reference image ${i + 1}: ${label}`).join('\n')}\n`
    : '';

  return `Generate a 3x3 cinematic storyboard contact sheet. Each of the 9 panels is ${orientation} (${aspectRatio}). The overall canvas is a uniform 3x3 mosaic with no borders, no gaps, and no separator lines between panels.

Scene environment: ${sceneStyle}
${refSection}
Characters (MUST match reference images exactly — same face, hair, skin tone, body type, clothing in every panel):
${characterDescriptions}

Panel layout (left-to-right, top-to-bottom):
Panel 1: ${shots[0]}
Panel 2: ${shots[1]}
Panel 3: ${shots[2]}
Panel 4: ${shots[3]}
Panel 5: ${shots[4]}
Panel 6: ${shots[5]}
Panel 7: ${shots[6]}
Panel 8: ${shots[7]}
Panel 9: ${shots[8]}

CRITICAL: Every panel must show the EXACT same character appearance as the reference images — identical face shape, facial features, eye color, hair style, hair color, skin tone, and costume. Do NOT alter any character's appearance between panels. Maintain exact same lighting and environment across all 9 panels. Panels must be seamlessly adjacent with NO borders, NO separators, NO white lines, NO black lines, NO gaps between panels. The grid must be a pure 3x3 image mosaic with zero padding. Each panel must be a complete standalone ${orientation} composition, not a cropped fragment.`;
}
